---
traefik_int_conf_global:
    sendAnonymousUsage: "{{ traefik_qs_send_anonymous_usage }}"

traefik_int_conf_entryPoints:
    web_http:
        address: :80

traefik_int_conf_entryPoints_https:
    web_https:
        address: :443

traefik_int_conf_entryPoints_https_redirect:
    web_http:
        http:
            redirections:
                entryPoint:
                    to: web_https
                    scheme: https

traefik_int_conf_providers:
    docker: {}

traefik_int_conf_log:
    level: "{{ traefik_qs_log_level }}"


traefik_int_conf_certificatesResolvers_le:
    letsencrypt:
        acme:
            email: "{{ traefik_qs_https_le_mail }}"
            tlsChallenge: {}
            storage: /letsencrypt/acme.json


traefik_conf_global: "{{
  traefik_int_conf_global | combine(traefik_confkey_global | default({}))
}}"
traefik_conf_entryPoints: "{{
  traefik_int_conf_entryPoints
  | combine(traefik_confkey_entryPoints
  | default({}))
}}"
traefik_conf_providers: "{{
  traefik_int_conf_providers | combine(traefik_confkey_providers | default({}))
}}"
traefik_conf_log: "{{
  traefik_int_conf_log | combine(traefik_confkey_log | default({}))
}}"
# traefik_conf_certificatesResolvers: "{{
#   traefik_int_conf_certificatesResolvers
#   | combine(traefik_confkey_certificatesResolvers
#     | default({})
#   )
# }}"


traefik_host_vol: /etc/traefik/
traefik_volumes:
    - /etc/localtime:/etc/localtime:ro
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "{{ traefik_host_vol }}traefik.yml:/etc/traefik/traefik.yml"
    - "{{ traefik_host_vol }}letsencrypt/:/letsencrypt/:rw"
    - traefik-data:/etc/traefik
