---
- name: Ensures elasticsearch ssl dir exists
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  with_items: 
    - "{{ elasticsearch_config }}/ssl"

- name: Copy elasticsearch certificate script
  template:
    src: "elasticsearch_certificate.sh.j2"
    dest: "{{ elasticsearch_config }}/elasticsearch_certificate.sh"
    owner: 1000
    group: 1000
    mode: 0770
  notify:
    - restart docker_elastic

- name: Elasticsearch Cert
  docker_container:
    name: "{{ elastic_hostname }}-cert"
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}
    state: started
    hostname: "{{ elastic_hostname }}-cert"
    pull: yes
    restart_policy: no
    command: bash /setup/elasticsearch_certificate.sh
    env:
      ELASTIC_PASSWORD: "{{ elasticsearch_password }}"
    volumes:
      - "{{ elasticsearch_config }}/ssl:/ssl"
      - "{{ elasticsearch_config }}/elasticsearch_certificate.sh:/setup/elasticsearch_certificate.sh"
    networks:
       - name: "{{ dockernet }}"
    purge_networks: yes
  notify:
    - restart docker_elastic

- name: Making sure that the cert files have been made
  wait_for:
    path:  "{{ item }}"
    delay: 10
    timeout: 30
    state: present
    msg: "Cert file is not present"
  ignore_errors: true
  with_items: 
    - "{{ elasticsearch_config }}/ssl/elastic-certificates.p12"
    - "{{ elasticsearch_config }}/ssl/elastic-stack-ca.p12"
    - "{{ elasticsearch_config }}/ssl/elastic-stack-ca.pem"

- name: Set Permissions
  file:
    path: "{{ item }}"
    state: file
    owner: 1000
    group: 1000
  with_items: 
    - "{{ elasticsearch_config }}/ssl/elastic-certificates.p12"
    - "{{ elasticsearch_config }}/ssl/elastic-stack-ca.p12"
    - "{{ elasticsearch_config }}/ssl/elastic-stack-ca.pem"