---
- name: Ensures elasticsearch ssl dir exists
  file:
    path: "{{ item }}"
    state: directory
    owner: 1000
    group: 1000
  with_items: 
    - "{{ elasticsearch_config }}/keystore"

- name: Copy elasticsearch keystore script
  template:
    src: "elasticsearch_keystore.sh.j2"
    dest: "{{ elasticsearch_config }}/elasticsearch_keystore.sh"
    owner: 1000
    group: 1000
    mode: 0770
  notify:
    - restart docker_elastic

- name: Elasticsearch Keystore
  docker_container:
    name: "elastic-keystore"
    image: docker.elastic.co/elasticsearch/elasticsearch:{{ elasticsearch_version }}
    state: started
    hostname: "elastic-keystore"
    pull: yes
    restart_policy: no
    command: bash /setup/elasticsearch_keystore.sh
    env:
      ELASTIC_PASSWORD: "{{ elasticsearch_password }}"
    volumes:
      - "{{ elasticsearch_config }}/keystore:/keystore"
      - "{{ elasticsearch_config }}/elasticsearch_keystore.sh:/setup/elasticsearch_keystore.sh"
    networks:
       - name: "{{ dockernet }}"
    purge_networks: yes
  notify:
    - restart docker_elastic

- name: Making sure that the keystore file have been made
  wait_for:
    path:  "{{ item }}"
    delay: 10
    timeout: 30
    state: present
    msg: "keystore file is not present"
  ignore_errors: true
  with_items: 
      - "{{ elasticsearch_config }}/keystore/elasticsearch.keystore"

- name: Set Permissions
  file:
    path: "{{ item }}"
    state: file
    owner: 1000
    group: 1000
  with_items: 
    - "{{ elasticsearch_config }}/keystore/elasticsearch.keystore"