- name: Destroy Terraform
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    backend_config:
      region: "{{ linode_state_bucket_region }}"
      bucket: "{{ linode_state_bucket }}"
      key: "{{ linode_state_bucket_key }}"
      access_key: "{{ linode_state_bucket_access_key }}"
      secret_key: "{{ linode_state_bucket_secret_key }}"
      endpoint: "{{ linode_state_bucket_endpoint }}"
    force_init: true
    variables:
      ansible_ssh_key_private: "{{ lookup('file', '{{ ansible_ssh_private_key_file }}') }}"
      li_token: "{{ linode_token }}"
