linode:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: "{{ lookup('env', 'PWD') }}/keys/devops"
    ansible_ssh_public_key_file: "{{ lookup('env', 'PWD') }}/keys/devops.pub"
    ansible_ssh_user: 'ansible'

    # Create Users
    users:
      - username: freddyal
        name: Freddy Al
        authorized_keys:
          # - "{{ lookup('file', '/home/ralph/devops.pub') }}"
          - "https://github.com/freddyal0x01.keys"
        home_create: yes
        append: yes
        home_mode: "0750"
        shell: '/usr/bin/zsh'
    
    users_authorized_keys_exclusive: yes
    security_sudoers_passwordless:
      - freddyal

    # ZSH Settings
    zsh_shared: yes
    
    # Docker Settings
    dockernet: "docker"
    docker_home_dir: '/opt/docker'

    # Pip Settings
    pip_install_packages:
      - name: docker
    pip_executable: pip3
    pip_package: python3-pip

    # NTP
    ntp_timezone: 'America/New_York'

    # Whitelist
    whitelist_ip: '0.0.0.0/32'

    #DNS
    domain_name: 'freddyal.com'